services:
  # Front-end (client)
  client:
    container_name: answer-client
    image: thibaultyvd/answer-client:latest
    restart: unless-stopped
    ports:
      - "3000:3000" 
    depends_on:
      - server

  server:
    environment:
      - DB_HOST=database
      - DB_USER=root
      - DB_PASSWORD=
      - DB_NAME=answer_db
    container_name: answer-back
    image: thibaultyvd/answer-back:latest
    restart: unless-stopped
    ports:
      - "3001:3001" 
    depends_on:
      - database 

  database:
    image: mysql:8.0
    container_name: answer_db
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=answer_db
      - TZ=Europe/Paris
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data: